apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: eu.gcr.io/fontys-276211/post
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m