spring:
  profiles:
  application:
    name: post-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081

---

spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:api
    username: sa

---